
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    #为了防止中文乱码，在URL中默认添加了?useUnicode=true&characterEncoding=UTF-8来使用UTF8编码，
    #&allowMultiQueries=true表示支持批量更新，因为我的电脑时区紊乱，无法启动项目，因此需要加&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 8080

mybatis:
  type-aliases-package: com.yan.demo
  mapper-locations: classpath:mapper/*.xml
